version: "3.8"

services:

  configserver:
    image: asingh434/configservice:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - ambank


  eurekaserver:
    image: asingh434/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - ambank
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  accounts:
    image: asingh434/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - ambank
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  accounts1:
    image: asingh434/accounts:latest
    mem_limit: 700m
    ports:
      - "8081:8080"
    networks:
      - ambank
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  loans:
    image: asingh434/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - ambank
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  cards:
    image: asingh434/cards:latest
    mem_limit: 700m
    ports:
      - "8091:8091"
    networks:
      - ambank
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

networks:
  ambank:
